import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../styles/index.scss';
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.variable}`}>
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
